### ISSUE TITLE
How to use flexiv rdk, like flexiv primitive, in ros2?

### ISSUE THREAD

**Issue by LebronX** [flexivrobotics/flexiv_ros2#4]
Do you have an example of using flexiv primitive in ros2? It seems like the current provided example is not related to the flexiv RDK.

**Comment by munseng-flexiv** [comment]
Hello @LebronX, 

There are no primitives in ROS2 as the `ros2_control` framework is designed to use only the robot's low-level control interfaces, e.g., joint position, velocity, and torque. Flexiv ROS2 uses the RDK non-real-time joint control APIs, e.g., [`SendJointPosition()`](https://www.flexiv.com/software/rdk/api/classflexiv_1_1rdk_1_1_robot.html#a5b00a5ed07ac4595d8d63d8f02396c3b)

If you want to use primitives, you could directly use RDK referred to this [example]( https://github.com/flexivrobotics/flexiv_rdk/blob/main/example/basics3_primitive_execution.cpp).

**Comment by munseng-flexiv** [comment]
Update:

To execute primitive in ROS2, you can create a standalone primitive execution action server using the RDK API [`ExecutePrimitive()`](https://www.flexiv.com/software/rdk/api/classflexiv_1_1rdk_1_1_robot.html#a45abfb0a498bc89042f1be587ef73025). But, at the same time, you cannot run the ROS2 control controller manager, because the RDK robot control mode is not the same (`NRT_PRIMITIVE_EXECUTION` vs. `NRT_JOINT_POSITION` in `write()` loop of ROS2 control hardware interface). 

Other limitations if not using the ROS2 control interface:
- all [ROS2 controllers](https://github.com/flexivrobotics/flexiv_ros2/blob/humble/flexiv_bringup/config/rizon_controllers.yaml) cannot be used including the `joint_trajectory_controller` being used by MoveIt to joint control the robot
- the `joint_states` topic is not updated -> you have to create a custom `joint_states_publisher` node to publish the joint states if you use RViZ or other simulation tools that subscribe to `joint_states` for robot visualization
